/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface IndexSettingsUpdate {
  primaryKey?: string
  searchableAttributes?: Array<string>
  displayedAttributes?: Array<string>
  filterableAttributes?: Array<string>
  sortableAttributes?: Array<string>
}
export interface GetDocumentsOptions {
  offset?: number
  limit?: number
  fields?: Array<string>
}
export interface GetDocumentsResults {
  results: Array<any>
  offset: number
  limit: number
  total: number
}
export interface SearchOptions {
  offset?: number
  limit?: number
  attributesToRetrieve?: Array<string>
}
/**
 * A single document hit in search results.
 *
 * JS shape: `{ id, score, attributes: { ...originalDocFields } }`
 */
export interface DocumentHit {
  /**
   * Document primary key (string for JS interop; milli uses u128 internally
   * but we expose the user-supplied string id when available).
   */
  id: string
  /** Ranking score. Higher is more relevant (milli uses BM25 + custom tweaks). */
  score: number
  /** The original document fields as JSON. */
  attributes: any
}
/**
 * Full search results.
 *
 * Mirrors the relevant subset of meilisearch-js's `SearchResponse`.
 */
export interface SearchResults {
  /** Matching documents, sorted by relevance descending. */
  hits: Array<DocumentHit>
  /** Estimated total matches (may be approximate for large indexes). */
  estimatedTotalHits: number
  /** Lower bound of processing time in milliseconds. */
  processingTimeMs: number
  /** The query string as executed (after normalization). */
  query: string
  /** Whether the query was empty (returns all docs by milli's defaults). */
  isEmptyQuery: boolean
}
export interface TaskDetails {
  receivedDocuments?: number
  indexedDocuments?: number
  searchableAttributes?: Array<string>
}
export interface TaskInfo {
  uid: number
  indexUid?: string
  status: string
  type: string
  details?: TaskDetails
  error?: string
  enqueuedAt: string
  startedAt?: string
  finishedAt?: string
}
/**
 * The top-level container for a collection of named indexes.
 *
 * Once constructed, an `Engine` is cheap to clone and can be shared across
 * threads — internal state is wrapped in `Arc` + `Mutex`/`RwLock`.
 */
export declare class Engine {
  /**
   * Create a new engine rooted at `basePath`. The directory must exist
   * (we don't `mkdir -p` to avoid surprising the user; pass an explicit
   * path that has been created).
   */
  constructor(basePath: string)
  /** List the UIDs of every index present on disk. */
  listIndexes(): Promise<Array<string>>
  /**
   * Create a new index with the given `uid` and `primary_key` (the field
   * name used as the document id). Fails if the index already exists.
   */
  createIndex(uid: string, primaryKey: string): Promise<void>
  /**
   * Open (or create-if-absent) an index by uid and return a handle.
   *
   * `primary_key` is required only when creating — if the index already
   * exists it's ignored.
   */
  getIndex(uid: string, primaryKey?: string | undefined | null): Promise<Index>
  /**
   * Delete an index by uid. Removes the on-disk directory and any cached
   * handle.
   */
  deleteIndex(uid: string): Promise<void>
  getTask(taskUid: number): Promise<TaskInfo>
  waitForTask(taskUid: number, timeoutMs?: number | undefined | null): Promise<TaskInfo>
}
/**
 * Handle to a single Meilisearch index.
 *
 * Cheap to clone (internal state is `Arc<Mutex<...>>`).
 */
export declare class Index {
  /** The uid of this index. */
  get uid(): string
  /** The configured primary key, or null if not set. */
  get primaryKey(): string | null
  /** Total number of documents currently stored in the index. */
  documentCount(): number
  getDocuments(options?: GetDocumentsOptions | undefined | null): Promise<GetDocumentsResults>
  /**
   * Bulk-load documents from a newline-delimited JSON string.
   *
   * Each line must be a JSON object representing one document. The primary
   * key (if configured on this index) is used to deduplicate — re-sending a
   * document with the same primary key replaces the previous version.
   *
   * Returns the number of documents indexed.
   */
  addDocumentsFromNdjson(ndjson: string): Promise<TaskInfo>
  updateSettings(settings: IndexSettingsUpdate): Promise<TaskInfo>
  search(query: string, options?: SearchOptions | undefined | null): Promise<SearchResults>
}
